package riscv.RV32;

public enum Commands {
    LUI, AUIPC, JAL, JALR, BEQ, BNE, BLT, BGE, BLTU, BGEU, LB, LH, LW, LBU, LHU,
    SB, SH, SW, ADDI, SLTI, SLTIU, XORI, ORI, ANDI, SLLI, SRLI, SRAI, ADD, SUB,
    SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND, NOP, ECALL, EBREAK,

    MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM, REMU,

    C_LWSP, C_SWSP, C_LW, C_SW, C_J, C_JAL, C_JR, C_JALR, C_BEQZ, C_BNEZ, C_LI, C_LUI,
    C_ADDI, C_ADDI16SP, C_ADDI4SPN, C_SLLI, C_SRLI, C_SRAI, C_ANDI, C_MV,
    C_ADD, C_AND, C_OR, C_XOR, C_SUB, C_NOP, C_EBREAK,

    UNKNOWN
}
